GET http://localhost:8000/api/items/
Content-Type: application/json

###

POST http://localhost:8000/api/items/
Content-Type: application/json

{
    "name": "Sample Item",
    "description": "This is a sample description."
}

###

GET http://localhost:8000/api/users/
Content-Type: application/json

###

POST http://localhost:8000/api/users/
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "first_name": "user",
    "last_name": "One"
}

### OpenSearch Cluster Health Check
GET http://localhost:9200/_cluster/health
Authorization: Basic admin:Str0ngP@ssw0rd!2024

